name: CICD
on: push
jobs:

#  _____             _   _                              
# /  __ \           | | (_)                             
# | /  \/ ___  _ __ | |_ _ _ __  _   _  ___  _   _ ___  
# | |    / _ \| '_ \| __| | '_ \| | | |/ _ \| | | / __| 
# | \__/\ (_) | | | | |_| | | | | |_| | (_) | |_| \__ \ 
#  \____/\___/|_| |_|\__|_|_| |_|\__,_|\___/ \__,_|___/                                                      
#  _____      _                       _   _             
# |_   _|    | |                     | | (_)            
#   | | _ __ | |_ ___  __ _ _ __ __ _| |_ _  ___  _ __  
#   | || '_ \| __/ _ \/ _` | '__/ _` | __| |/ _ \| '_ \ 
#  _| || | | | ||  __/ (_| | | | (_| | |_| | (_) | | | |
#  \___/_| |_|\__\___|\__, |_|  \__,_|\__|_|\___/|_| |_|
#                      __/ |                            

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Dependencies
        run: npm i

      - name: Build the code
        run: npm run build

