name: CICD
on: push
jobs:

#  _____             _   _                              
# /  __ \           | | (_)                             
# | /  \/ ___  _ __ | |_ _ _ __  _   _  ___  _   _ ___  
# | |    / _ \| '_ \| __| | '_ \| | | |/ _ \| | | / __| 
# | \__/\ (_) | | | | |_| | | | | |_| | (_) | |_| \__ \ 
#  \____/\___/|_| |_|\__|_|_| |_|\__,_|\___/ \__,_|___/                                                      
#  _____      _                       _   _             
# |_   _|    | |                     | | (_)            
#   | | _ __ | |_ ___  __ _ _ __ __ _| |_ _  ___  _ __  
#   | || '_ \| __/ _ \/ _` | '__/ _` | __| |/ _ \| '_ \ 
#  _| || | | | ||  __/ (_| | | | (_| | |_| | (_) | | | |
#  \___/_| |_|\__\___|\__, |_|  \__,_|\__|_|\___/|_| |_|
#                      __/ |                            

  build:
    needs: [security-audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        run: npm i

      - name: Build the code
        run: npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Test the code
        run: npm run test

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Lint the code
        run: echo npm run lint

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check for security issue
        run: echo DO this another time when Andrei has the patience #npm audit --audit-level=crititcal #or "high"

  static-analysis:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
        
      - run: echo This takes entirely too long!
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: javascript
      
      # - name: Perform Analysis
      #   uses: github/codeql-action/analyze@v1
